services:
  chroma:
    image: chromadb/chroma:1.4.2.dev97
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/.chroma # Mount a named volume for persistence
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=*
volumes:
  chroma_data: